ister_gui.py
=> Fix pep8 and pylint complaints in ister_gui

ister_gui.py
Provide feedback in the form of 'Step x of n' where n can grow depending
on the user's choices during the install process.
=> Provide progress feedback to user

ister_gui.py
=> Fix confirm_disk_wipe2 screen to show correct steps

ister.py, ister_gui.py, ister_test.py
The gui displays both http and https proxies detected in the
environment and allows user to set them manually.
=> Auto-detect and allow user to set http/https proxies

ister_gui.py, ister_test.py
If the hardware clock is not set to the current time whecn SWUPD runs
ssl-cert validation errors can occur and the installer will abort.
Set the hardware clock using the 'Date' header from the http response
gathered when checking for a network connection.
=> Set hardware clock on successful http connection

ister_gui.py, ister_test.py
Allows the user to select which path to take:
- Install leads to install path
- Repair mounts the host os disk and runs swupd verify --fix in
its chroot.
- Shell gives the user a shell in the host os disk chroot
- Update Installer runs swupd update in the installer image and
restarts the installer, giving the user some survival options.
=> Add ChooseAction screen for shell/repair/install paths

ister_gui.py
Update button foreground colors to light cyan in response to feedback.
=> Update button colors to light cyan

ister_gui.py
- Alert user when automatically formatting root partition
- Change 'Done' buttons to 'Next' for cconsistency
=> Make small UX improvements

ister_gui.py
=> Replace os-clr-on-clr with user-basic

ister_gui.py
When a user selects bundles or configures their partitions, this
information is saved and displayed if they return to the screen.
=> Save bundle and partition information screens

ister_test.py
=> Update test to reflect read->readlines change

ister_gui.py
- Change wording from 'Reset network to default configuration' to 'Reset
network to DHCP configuration'. This button only shows up when static
configuration is set and there is no guarantee that default is 'DHCP.'
- Instead of tracking whether static has been set using a variable, use
a check against the static network file.
- Change disk wipe warning to indicate the wipe will not occur until the
last step.
- Only advance from StaticIPStep when a user hits the 'Next' button if
the static network configuration has been properly set. It was
previously possible to choose DHCP, back up a step, choose static IP,
press 'Next' without entering configuration and have DHCP still set.
=> Make several UI changes in response to review

ister_gui.py
Instead of guessing at a time to sleep, poll systemctl status output
until network services are up.
=>  Poll systemctl status output when restarting network

ister_gui.py
- Fix bug where removing partition after setting mount point caused
exception.
- Only display 'auto format on root' message when user does not select
the format option on root mountpoint.
- Remove old duplicate mount point if user enters that mount point
again.
=> Make several fixes to mount point screen

ister_gui.py
Remove network-basic and sysadmin-basic bundles from the required
bundles list and add them to a "default bundles" list. The default
bundles are selected by default but the user is able to deselect them.
This keeps the "required" size of the OS small, but indicates to the
user which bundles are commonly used because they are selected by
default.
=> Reduce required bundles and add default bundles

ister_gui.py
Mount `/sys` and `/proc` to the chrooted environment and set the HOME
environment variable so vi and vim can be used.
=> Set up proper chroot environment

ister_gui.py
The 'Repair' option in Ister was failing to complete the repair due to a
failed network connection in the chroot. Instead of chrooting and trying
to set up a network, the path to the mounted host OS can be provided to
swupd via the --path option. This removes the complicated chroot
requirements and fixes the 'Repair' option.
AKA: RTFM
=> Make use of swupd's --path option for repair

ister_gui.py
This function failed to find partitions on a VMBUS connection when
parsing /sys/block. Parsing of /sys/block is entirely unnecessary,
however, as all relevant information can be found in the existing lsblk
output - and will be consistent across virtualization technologies.
This patch greatly simplifies the get_list_of_disks() function by
relying only on lsblk output.
=> Fix get_list_of_disks() parsing for windows VMs

ister.py, ister_test.py
Full explanation in the commit itself. It may be that you intend for this behaviour, but in case
it isn't, here's an alternative. ^^
=> RFE: Add sudo users to the sudo group, not to the sudoers config file

.travis.yml, ister_test.py, requirements.txt
Ignore this until it works.
update: this works
Several tests had to be modified to properly mock internal functions and subprocess calls.
=> Add configuration files for Travis CI

ister.py, ister_test.py
When doing physical installations, the statedir argument was being
largely ignored incorrectly due to the use of the bind mount. Rework the
bind mount usage and at the same time fixup the creation of the
directory to set the mode to only be accessable by the owner (root).
Also fixup cleanup to handle the potential new location of the statedir.
=> Rework statedir handling for physical installs

ister_gui.py
Add timeout messages for network service startup and network detection
if network information is not found. These messages are removed/replaced
when network is set up.
Does not change GUI flow - no tests modified or added.
=> Add timeout messages for network service/detection

ister_gui.py
When the user enters a static IP configuration for the installer, the
target static IP configuration fields are pre-populated with the
settings. This prevents the user from having to enter the configuration
twice.
=> Persist installer network config to target screen

ister.py, ister_gui.py, ister_test.py
Make Ister pylint and pycodestyle clean. Many exceptions are removed, and those that remain are renamed to use their title instead of error number.
=> Make pylint and pycodestyle fixes

ister_gui.py
For the static network configuration steps (installer and target), add a
pop up to list the interfaces available on the system. This allows users
to decide which interfaces to configure without having to switch ttys
and run "ip a".
=> Add pop ups for interface configurations

ister_gui.py
Instead of reading the list of disks only once when ister_gui is
initializing, read them every time the disk partition screen is reached.
This fixes a bug where slow-loading devices have not loaded by the time
the available disks are determined and are therefore never discovered by
ister, causing the installation to be impossible.
The choice was made to read the disks every time instead of just until
some devices are found since some devices may load faster than others.
=> Read available disks every time screen is reached

installer-design, ister.py, ister_test.py, post-chroot.sh, post-non-chroot.sh, pre-post.json, shell-nonchroot-post.json
Add additional script and shell command handlers to:
* Run shell commands prior to installation starting
* Run post install shell commands both in and out of the installation chroot
* Run post install scripts inside the installation chroot (running scripts outside of the chroot was already supported)
=> Pre post handlers

ister.py, ister_test.py
When using dd to create a sparse file seek should be set to be the
offset and count should be set to 0.
=> Fix sparse file creation

ister.py, ister_gui.py, ister_test.py
Fixes:
* gui swap detection
* dd not using sparse file creation
* dd to use megabyte offsets for parted
=> Resolve dd and swap bugs

ister_gui.py
A subprocess.check_output call is causing a crash in ister making it
impossible to complete the install process. To fix this and avoid
potential future issues, add exception handling to all check_output
calls in the gui.
=> Catch exceptions from check_output calls

installer-config-vm.json, ister_gui.py
Also update installer config image size
=> Move openssh-server to the default list

ister.py, ister_test.py
Update changes from #136 to pass tests.
=> Add target options

ister.py
Improve ister and allow specifying the SSH key by value as well.
=> Allow specifying authentication keys by value

ister.py, ister_test.py
I did not initially want to do this, but as I keep contributing to ister, the pylint complaints bother me more and more. Indeed, there are many of them, and every time I run pylint, I am having hard time distinguishing between the complaints I introduced and the "prior art" complaints. My previous pull request even introduced one complaints.
I am not a pylint natsi, but this tool did help me a lot in the past and it is very useful. In case of ister pylint does not report any major issues, but it does report a lot of stylistic problems. And this noise bothers me.
This pull request cleans up the code and makes pylint happy. It addresses all the complaints except of this one:
W:1403, 0: TODO: Iterate over all interfaces in the future? (fixme)
I decided to leave it as is.
This pull request …
=> Pylint cleanus

autoinstall.expect, encryption.expect, ister_gui.py, maninstall.expect
Update product name and text on install screen
Signed-off-by: Mark D Horn <mark.d.horn@intel.com>
=> Fix the OS naming
