bryteise/ister

ister.py, ister_test.py
Avoid creating the swupd state within the image creation directory by providing a -S/--state flag and passing it to swupd.
Patch created by Leoandro Dorileo.
Added unit tests.
=> add --state flag and pass it to swupd

ister_gui.py
When a user checks the box to opt-in on the telemetry screen the
focus jumps to the 'Next' button.
=> Jump focus to 'Next' on telemetry opt-in

ister_gui.py
When partition names are 9 characters or more they bump up against
the partition size in the disk wipe confirmation menu. Add a space
after the partition name so this will not happen.
Also fix a few pep8 complaints:
- 677: line too long
- 727: too many blank lines
- 861: continuation line under-indented
- 862: continuation line under-indented
=> Add space after partition name in disk wipe confirmation, pep8 fixes

ister_gui.py
This class can be instantiated for the sole purpose of retreiving a
list of required bundles. In this case it should not be necessary to
pass cur_step and tot_steps arguments since they will not be used.
This sets default values of None and only builds the progress widget
if values have been passed to the constructor. This prevents a crash
when the installation confirmation step is reached.
=> Add checks for BundleSelectorStep arguments

ister.py, ister_gui.py, ister_test.py
Display network requirements and give indication of whether
the system is able to connect to clearlinux.org or not. Allow the
user to configure a static ip address, gateway, and interface for the
installer to use.
Also add configurable proxy to installer gui and pass to swupd via the
json template. This way, if pacrunner is not working the user can
define their own proxies to connect to clearlinux.org for the
installation.
=> Add network check on splash screen

ister.py, ister_test.py
Users often complain about ister_gui not giving any status indication
when swupd starts up during the last step of the installation. This
patch displays the swupd output in the GUI alert so users can at
least see that the process is not frozen.
=> Show swupd --install output in GUI

ister_gui.py, ister_test.py
After UX review, users were confused and intimidated by the first
screen being a network configuration screen. This adds a screen that
informs the user they are installing Clear Linux and a brief message
about Clear.
Adding this screen required an update to the progress messages at the
top of each consecutive screen.
=> Add first screen introduction to Clear Installer

ister_gui.py
UX review identified the buttons as blending into the background of
the reset of the UI text. It was not clear they were selectable just
from the '< >' brackets. This patch adds a dark blue color to the
buttons to make them stand out.
=> Change UI button foreground color to dark blue

ister_gui.py
os-utils is being deprecated. This patch replaces the os-utils bundle
in the required bundles list with network-basic and sysadmin-basic for
core system management utilities.
=> Replace deprecated bundle in required bundle list

ister_gui.py
This patch allows the user to continue to the next screen if they
modified the interface/ip/gateway information unintentially and
did not attempt to set it.
The interface settings should not restrict the user from advancing
to the next screen in the installer. Even if there is no network
connection, they could still choose an action other than install
on the ChooseAction screen.
=> Allow user to continue with undetected interface settings

ister_gui.py, ister_test.py
* Redesign network screen to group like config options 
This was a confusing screen because it was not clear which buttons
were related to which configuration field. They are not grouped in
a logical manner and the < reset network > button only appears when
it is relevant.
Also remove the .8 second sleep on startup since this is no longer
the first screen. The time the user spends on the splash screen will
allow the network units to start up.
* Add optional DNS setting to static IP configuration
=> Redesign network screen

ister_gui.py
This is a proposal to change ister_gui to a dark theme. Personally I like this better than light gray on dark blue. Please see screenshots below.
(can you spot the bug ^^^?)
=> Change ister GUI to a dark theme

ister_gui.py, ister_test.py
* Use libcurl's WRITEFUNCTION to mask output to STDOUT
Overwriting HEADERFUNCTION simply adds the curl output to the buffer,
but overwriting WRITEFUNCTION also masks the output to stdout so users
aren't spammed with the output of the curl command.
* Separate static settings from detected settings
The static IP configuration fields were pre-populated with the
detected configuration data. This patch moves the detected
configuration to the right side of the screen, out of the way.
The static IP fields are now initially blank.
=> Further reorganizing of the Network Requirements screen

ister_gui.py, ister_test.py
The static configuration button on the network requirements screen is
disabled and grayed out for the user until text is added to the three
required static configuration edit boxes.
=> Disable static configuration button until requirements met

ister.py, ister_gui.py, ister_test.py
* Move static network validation to user edits
As the user edits the static IP configuration boxes, their input is
checked in real-time as they type. Once the field they are editing is
detected as a valid interface/IP address, the field caption turns
green, notifying the user of a valid configuration. The button to set
the static configuration does not activate until all required fields
are valid.
Moving this logic to before button activation allows the removal of a
lot of error handling complexity in the handler() function since the
user is not allowed to press the button until the input is valid.
Because of this, this patch also includes considerable simplification
to the NetworkRequirements class.
* Allow user to unset https_proxy
User can unset their previously entered https_proxy on …
=> Move static network validation to user edits, allow proxy unset

copy_files.sh, update_installer.sh
These scripts help when testing changes made to the installer.
- copy_files.sh
Copies arbitrary files into image at user-provided file path.
- update_installer.sh
Copies ister.py and ister_gui.py into correct locations in
user-provided images.
=> Add scripts helpful for testing and development

ister_gui.py, ister_test.py
A subnet mask is required for static networks. This adds the ability to
define one for the installer during the network requirements step.
Thanks to George Kramer for pointing this out. This has been tested on bare metal.
=> Add subnet mask field to network configuration

ister_gui.py, ister_test.py
Use the same logic to validate IP addresses for the host static IP step
as is used in the installer static IP configuration. Separates the logic
out into a NetworkControl class for reuse.
=> Update Static IP Step for host

ister_gui.py
Sending CTRL-C to the installer does not do anything but show a
meaningless python stacktrace and freeze the installer. This signal
should be ignored altogether.
=> Ignore SIGINT as it only freezes the TTY

spinup.sh
Add spinup.sh, which allows a user to spin up ./installer.img with
./OVMF.fd bios file to quick-test installer. This is a very simple
script meant to be sent to testers along with the other required files
so they can test the installer with minimal effort.
Requires vncviewer and qemu as dependencies.
Usage:
```bash
./spinup.sh <port number>
./spinup.sh     # port number defaults to 2233
```
=> Add simple VM spinup script for testing

ister_gui.py
This fixes a bug where a configuration is saved in which a mount point
is associated with a certain partition, then the user changes the mount
point associated with that partition. Since the configuration keys off
the mount point, not the partition number, there would exist two mount
points for the same partition, causing a fatal error.
This bug could be reproduced by:
1. User sets mount point (e.g. /home) on a partition (e.g. partition 2)
and hits "Next" causing Ister to save the configuration.
2. User hits "Previous" and re-navigates to the manual mount point
screen.
3. User changes the mount point on partition 2 to a different name (e.g.
/boot) and hits "Next".
The above steps caused an error alert and failure exit from Ister.
This patch removes old duplicate entries if they exist at …
=> Remove duplicate mount point partition information

ister_gui.py
An 'Exit' option was not offered until the screen to choose automatic or
manual install. This made sense when installation was the only user
option, but Ister now provides Repair and Shell options as well. The
Exit option should be presented at this point.
Resolves CLEAR-1844
=> Add 'Exit' button to path option screen

ister_gui.py
Since swupd is quiet for several minutes while "copying missing files",
add a message that the installation may take a few minutes so users do
not think the installation has hung.
Resolves CLEAR-1842
=> Add wait time message to last installer step

ister_gui.py
The first time a user reaches the NetworkRequirements screen, poll
systemctl status systemd-networkd for an "Active" message.
This fixes the issue where a user tabs past the first screen fast
enough that the network service had not loaded yet, causing the screen
to display a "not connected" message. Now the first time a user reaches
that screen the network service will be started and any "not connected"
message will be a result of an actual network test.
=> Wait for network service on first network screen load

autoinstall.expect, ister_gui.py, maninstall.expect
Adds a keyboard selection menu to ister_gui, which allows the user to
select the layout of their keyboard. The keyboard mapping defaults to
us.
Requires the addition of `kbd` to the os-installer bundle.
=> Add keyboard selection screen to installer gui

ister.py, ister_gui.py, ister_test.py
Instead of always testing the clearlinux website as the network
available standard, make use of the content and version urls passed in
as arguments. At the same time update the clearlinux urls to reflect the
cdn to the update content instead of the main page similar to how the
swupd-client itself works.
=> Allow configuration to dictate network testing

installation-image-post-update-version.py, installer-config.json
Add a five-second systemd-boot timeout to the installation image to
allow the user the time to edit the kernel cmdline by pressing 'e'.
Testing also required removing os-core-dev bundle from installer-config.json.
=> Add systemd-boot five-second timeout

ister_gui.py
This has caused much confusion with users thinking they were defaulted
to ANSI-dvorak. The default 'us' keyboard now shows up at the top of the
list, with an asterisk to show it was selected by default.
=> Move 'us' default keyboard to top of list

ister_gui.py
Allow user to set an interface pattern instead of requiring the exact
and existing NIC in the static interface field. This allows users to set
a static network configuration when no interfaces have been configured.
**WIP**
I'll be looking into displaying the names of all available NICs. This was opened at this point since this is a quick fix to an issue users are seeing, and we may want to merge as-is. Adding part two of this may be a rather involved process.
=> Allow generic static configuration for installer

ister_gui.py, ister_test.py
Instead of stripping all digits from the partition name and calling it
the device name, use the output of lsblk -no pkname <partition> to find
the real device name.
This fixes bugs that occur when the device name actually has digits in
it (e.g. /dev/nvme0n1).
=> NVME partition support

ister.py, ister_gui.py, ister_test.py, maninstall.expect
Allow the user to append parameters to the kernel cmdline. This screen
shows an example of the sane defaults used in Clear Linux for native
kernel. The appended parameters are added to <target>/etc/kernel/cmdline
and clr-boot-manager update is run to append the parameters to the boot
entry.
=> Add screen to append to kernel cmdline

ister.py, ister_test.py
Switch to dd instead of qemu-img for creating virtual disks. Also enable stderr output to be output to the console even if the program didn't exit with a non-zero return code.
=> Use dd not qemu img

ister_gui.py
Do not reject '.' characters in hostnames as a way to enable users to
enter a FQDN when entering their hostname.
=> Enable users to enter fully qualified domain names

ister_gui.py, maninstall.expect
Allow users to select the openssh-server through the ister_gui manual
bundle selection page.
=> Allow openssh-server to be installed through the gui

ister.py, ister_test.py
In order to allow installation in more memory constrained situations,
make use of the install target's swap partition if available before
running swupd.
=> Use target swap space during install if available

ister_gui.py
Add a message warning users that setting the static IP on the installer
may require a "Refresh" of the screen to see the changes reflected in
the UI. This approach is better than blocking the reload of the screen
until the new setting have taken place.
=> Add "may require Refresh" message to static IP settings

ister_gui.py
Similar to 92305ebd92dab070e7c6dafc0acd56b6cafe7547, except instead of
handling the error in the callers of get_disk_info, fix it in the
function directly since all but one of the callers were checking for
empty results anyway.
=> Add exception handling to get_disk_info

ister.py, ister_test.py
The current install approach favors disk space by allowing for the state
dir to exist outside of the target dir.  However, the two directories
can exist across block device boundaries.  To favor time to install,
adding an option to relocate the state dir into the target dir so they
are located within the same block device.  This can reduce install time
by as much as 60%.  Once the install has completed, the state dir is
removed from the target dir.
This has a couple of side effects.  When this option is used, the
template needs to allocate space for the state dir in addition to actual
content.  Additionally, this option cannot be used in conjunction with
the statedir option, as the state dir in this case is automatically
derived.  Because of these side effects, this option is not enabled …
=> Add option for moving statedir into targetdir

ister.py, ister_test.py
Turn off swap devices that were enabled by ister during image
creation/installation. This resolves an issue where loop devices could
not be cleaned up after image creation.
=> Disable swap devices enabled by ister

dnf-post-update.sh, ister.py, ister_test.py
In test scenarios, work to create a swupd update stream is not needed
and increases image generation time.  If content for a test scenario can
be supplied as a package repository, then dnf can be used to do an
install of packages in the same way mixer generates chroots.
To support a define-and-run approach with ister, template files may
define an additional "PackageManager" key, which may be either "dnf" or
"swupd", if not defined to preserve backwards compatbility.  In the case
where the package manager is swupd, the list of bundles remains the same
as it is today.  In the case where the package manager is dnf, the
bundle list is treated as a package list that is used during a dnf
install.
Much like how content and version URLs may be passed at the command line
for swupd, to pass package …
=> Add support for installing content with dnf

Makefile.am
When getting going with ister and Clear, new users will expect to be
able to look in /usr/share for reference implementations of how to do
certain tasks.  Providing a reference for physical images and virtual
images will help users get going more quickly.  This would also allow
public documentation to be updated to let users copy files they already
have locally to keep them going with their task.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Add reference JSON for virtual images

ister.py, ister_test.py
Ister and swupd run ldconfig after an install redundantly.  We want to
have ister default to letting swupd run its post install triggers, or
having a user run these manually in the same way that swupd would with
their post script, rather than replicating part of them itself.  Running
ldconfig differently in both instances has the side-effect of removing
broken library symlinks from an install.
Signed-off-by: George T Kramer <george.t.kramer@intel.com>
=> Do not run ldconfig in post install nonchroot

ister.py, ister_gui.py, ister_test.py
Summary of changes:
- set argument default to None when cmdline value not specified (no hardcoding)
- allow user to optionally modify values independently for the content or version URL's to alternate mirrors
- if there is a URL modification, or a command line value that verify as 'good', ister will write the values to the target OS
=> Adding custom mirror URL fields to installer

ister.py
It is hard to diagnose ister failures because of 2 reasons:
1. The stacktrace is hidden. Let's have it when using the debug loglevel.
2. The error message is hidden. Let's always have it - users will appreciate more visibility into the issue even when loglevel is non-debug.
=> Improve error messages

ister.py, ister_test.py
This pull requests makes it possible to change the 'root' user via 'ister.json', for example change root password and install root user SSH key. On top of this, the pull request fixes few bugs and introduces few improvements.
My use-case is the following. I have a SUT (System Under Test) in a fully isolated environment. I want my fully automated and unattended installation to set a pre-defined root password, root SSH key, and enable root SSH login. As simple as this. And I do not want to bring up 'cloud-init' server just for this simple purpose.
Here is the ister.json template that I use. It only works with patches introduced in this pull request. The ister.json below is acutally a Jinja2 template, which I render to get the final 'ister.json'. But this is an unimportant detail and I …
=> Changing root user

ister.py, ister_test.py
This pull request includes the other 2 requests I sent earlier - "pylint cleanups" and "changing root user".
I will rebase this pull request f needed later.
This pull request adds these 3 commits:
Enhance run_command()
ister: split run_command()
ister_test: improve tracability
With these changes 'run_command()' is much nicer and now I can actually see 'swupd' progress "real-time":
Running command stdbuf -o 0 swupd verify --install --path=/mnt/sysimage --manifest=latest --contenturl=http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/update --versionurl=http://linux-ftp.jf.intel.com/pub/mirrors/clearlinux/update --statedir=/var/lib/swupd
Verifying version 25040
Downloading packs...
Extracting bootloader pack for version 24630
Extracting dev-utils pack for version 25040
Extracting git pack …
=> Enhance run command

ister.py, ister_test.py
This patch speeds up ister installer by removing the 15 seconds unconditional sleep. I understand why this sleep was added, but this is a very crude solution for the problem. This pull request offers a nicer solution - instead of sleeping for 15 seconds we keep trying with 15 seconds timeout.
This pull request also implements several cleanups resulting in a bit more structured and readable code.
This pull request includes the 3 previous pull requests. It is based on top of the "enhance run_command" work. I'll rebase it if/when needed. Comparing to the "enhance run_command" pull request, this adds the following patches:
Remove useless os.unlink
Smarter ister.conf download
Generalise 'check_kernel_cmdline()'
Simplify check_kernel_cmdline
=> Remove 15 secs sleep

ister-provision.service, ister.py, ister.service
Do not reboot the system is ister failed. Improve the 'ister.exit' option handling.
=> Reboot only on success

ister_gui.py
https://lwn.net/Articles/682276/
=> Add a filter in get_list_of_disks to prevent it to pick up devices like /dev/mmcblk0rpmb
